kind: pipeline
name: default

steps:
  - name: install
    image: node:latest
    commands:
      - npm set registry https://$${NEXUS_NPM_REPO}/
      - npm set //$${NEXUS_NPM_REPO}/:_authToken=$${NPM_TOKEN}
      - npm ci
    environment:
      NEXUS_NPM_REPO:
        from_secret: NEXUS_NPM_REPO
      NPM_TOKEN:
        from_secret: NPM_TOKEN
  - name: build
    image: node:latest
    commands:
      - npm run tsc
  - name: publish
    image: node:latest
    commands:
      - npm set registry https://$${NEXUS_NPM_REPO}/
      - npm set //$${NEXUS_NPM_REPO}/:_authToken=$${NPM_TOKEN}
      - npm publish
    environment:
      NEXUS_NPM_REPO:
        from_secret: NEXUS_NPM_REPO
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    when:
      event:
        - tag
  - name: notify
    image: drillster/drone-email
    environment:
      PLUGIN_HOST:
        from_secret: MAILGUN_SMTP_HOST
      PLUGIN_FROM:
        from_secret: MAILGUN_SMTP_SENDER
      PLUGIN_RECIPIENTS:
        from_secret: EMAIL
      PLUGIN_USERNAME:
        from_secret: MAILGUN_SMTP_USERNAME
      PLUGIN_PASSWORD:
        from_secret: MAILGUN_SMTP_PASSWORD
      PLUGIN_RECIPIENTS_ONLY: true

---
kind: secret
name: EMAIL
get:
  path: secret/drone-ci
  name: EMAIL

---
kind: secret
name: NEXUS_NPM_REPO
get:
  path: secret/drone-ci
  name: NEXUS_NPM_REPO

---
kind: secret
name: NPM_TOKEN
get:
  path: secret/drone-ci
  name: NPM_TOKEN

---
kind: secret
name: MAILGUN_SMTP_PASSWORD
get:
  path: secret/drone-ci
  name: MAILGUN_SMTP_PASSWORD

---
kind: secret
name: MAILGUN_SMTP_HOST
get:
  path: secret/drone-ci
  name: MAILGUN_SMTP_HOST

---
kind: secret
name: MAILGUN_SMTP_USERNAME
get:
  path: secret/drone-ci
  name: MAILGUN_SMTP_USERNAME

---
kind: secret
name: MAILGUN_SMTP_SENDER
get:
  path: secret/drone-ci
  name: MAILGUN_SMTP_SENDER
