kind: pipeline
name: default

steps:
- name: install
  image: node:latest
  commands: 
  - npm set registry https://$${NEXUS_NPM_REPO}/
  - npm set //$${NEXUS_NPM_REPO}/:_authToken=$${NPM_TOKEN}
  - npm ci --only=production
  environment:
    NEXUS_NPM_REPO:
      from_secret: NEXUS_NPM_REPO
    NPM_TOKEN:
      from_secret: NPM_TOKEN
- name: build
  image: node:latest
  commands:
  - npm run tsc
- name: publish
  image: node:latest
  commands:
  - npm set registry https://$${NEXUS_NPM_REPO}/
  - npm set //$${NEXUS_NPM_REPO}/:_authToken=$${NPM_TOKEN}
  - npm publish
  environment:
    NEXUS_NPM_REPO:
      from_secret: NEXUS_NPM_REPO
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  when:
    event:
    - tag
- name: notify
  image: drillster/drone-email
  host: smtp.gmail.com
  from: "${NOTIFY_EMAIL_USERNAME}@gmail.com"
  environment: 
    EMAIL_HOST: "smtp.gmail.com"
    PLUGIN_FROM:
      from_secret: NOTIFY_EMAIL_ADDRESS
    EMAIL_RECIPIENTS:
      from_secret: EMAIL
    PLUGIN_RECIPIENTS_ONLY: true
    EMAIL_USERNAME:
      from_secret: NOTIFY_EMAIL_USERNAME
    EMAIL_PASSWORD:
      from_secret: NOTIFY_EMAIL_PASSWORD
  when:
    status: [ success, changed, failure ]