kind: pipeline
name: default

steps:
  - name: install
    image: node:latest
    commands:
      - npm ci
  - name: build
    image: node:latest
    commands:
      - npm run tsc
  - name: publish
    image: plugins/npm
    settings:
      username:
        from_secret: PUBLIC_NPM_USERNAME
      password:
        from_secret: PUBLIC_NPM_USERNAME
      email:
        from_secret: EMAIL
    when:
      event:
        - tag
  - name: notify
    image: drillster/drone-email
    environment:
      PLUGIN_HOST:
        from_secret: MAILGUN_SMTP_HOST
      PLUGIN_FROM:
        from_secret: MAILGUN_SMTP_SENDER
      PLUGIN_RECIPIENTS:
        from_secret: EMAIL
      PLUGIN_USERNAME:
        from_secret: MAILGUN_SMTP_USERNAME
      PLUGIN_PASSWORD:
        from_secret: MAILGUN_SMTP_PASSWORD
      PLUGIN_RECIPIENTS_ONLY: true
    when:
      status: [failure]

---
kind: secret
name: EMAIL
get:
  path: secret/drone-ci
  name: EMAIL

---
kind: secret
name: PUBLIC_NPM_USERNAME
get:
  path: secret/drone-ci
  name: PUBLIC_NPM_USERNAME

---
kind: secret
name: PUBLIC_NPM_PASSWORD
get:
  path: secret/drone-ci
  name: PUBLIC_NPM_PASSWORD

---
kind: secret
name: MAILGUN_SMTP_PASSWORD
get:
  path: secret/drone-ci
  name: MAILGUN_SMTP_PASSWORD

---
kind: secret
name: MAILGUN_SMTP_HOST
get:
  path: secret/drone-ci
  name: MAILGUN_SMTP_HOST

---
kind: secret
name: MAILGUN_SMTP_USERNAME
get:
  path: secret/drone-ci
  name: MAILGUN_SMTP_USERNAME

---
kind: secret
name: MAILGUN_SMTP_SENDER
get:
  path: secret/drone-ci
  name: MAILGUN_SMTP_SENDER
